#----------------------------------------------------------------------
# Export-root configurator
#----------------------------------------------------------------------

# kvm on power label
export KOP_LABEL := IBM_PowerKVM

# kvm on power stream
export KOP_STREAM := 2.1.0

# will be printed on <iso>/.discinfo
export DISCINFO_STR := $(KOP_LABEL) $(KOP_STREAM) 

# kvm on power version
export KOP_VERSION_LABEL := 2.31

# kvm on power release
export KOP_RELEASE_LABEL := 0

# build timestamp
export TIMESTAMP := $(shell scripts/timestamp.sh)

# kvmonpower files
export KOP := $(shell pwd)

# kvmonpower release file
export KOP_RELEASE := $(KOP)/releases/release_$(TIMESTAMP)

# build directory
export BUILD_DIR := $(KOP_RELEASE)/tmp

# rootfs directory
export ROOTFS_DIR := $(BUILD_DIR)/rootfs

# overlay directory
export OVERLAY_DIR := ./overlay

# dvd directory
export DVD_DIR := $(BUILD_DIR)/dvd

# rpm directory
export RPM_DIR := $(BUILD_DIR)/rpm

#----------------------------------------------------------------------
# ISO name variables
#----------------------------------------------------------------------

# iso version number = stream.service
export ISO_VERSION := 2.1.0.2

# iso build number = build.respin
export ISO_BUILD := 31.0

# iso milestone
export ISO_MILESTONE := service

#----------------------------------------------------------------------
# Frobisher configuration
#----------------------------------------------------------------------

# Frobisher repository
export REPO_DIR := $(REPOS_BASE_DIR)/$(VENDOR)/$(STREAM_VERSION)/repo
export RPM_PKVM_DIST=.el7
export RPM_TARGET=s390x
export WORKSPACE=${PWD}/workspace

